_prefs: 
  mapid: zingbot.ffd744cf
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.1419
  - 40.567
  - 9
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 13
minzoom: 6
name: Emotional_style Two
source: "mapbox:///zingbot.6e7fa45d"
styles: 
  - style.mss
template: ''
